DROP DATABASE IF EXISTS mywebsite;

CREATE DATABASE IF NOT EXISTS mywebsite DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci;

grant all on mywebsite.* to redaktor@localhost identified by 'tajnehaslo';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON mywebsite.* TO redaktor@localhost WITH GRANT OPTION;

USE mywebsite;

CREATE TABLE CONTENT_TYPE (
    T_ID INT(2) NOT NULL AUTO_INCREMENT,
    CONTENT_NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY(T_ID)
) ENGINE=InnoDB;

CREATE TABLE CONTENT_ITEM (
    C_ID INT(100) NOT NULL AUTO_INCREMENT,
    CONTENT_ID INT(2) NOT NULL,
    HEADER VARCHAR(200) NOT NULL,
    CONTENT LONGTEXT NOT NULL,
    LANG ENUM('e','p') NOT NULL,
    ID_SECOND INT(100) NOT NULL,
    PRIMARY KEY(C_ID),
    CONSTRAINT CONTENT_TYPE_ID FOREIGN KEY(CONTENT_ID) REFERENCES CONTENT_TYPE(T_ID)    
) ENGINE=InnoDB;

CREATE TABLE USERS (
    U_ID INT(3) NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    PRIMARY KEY(U_ID)
) ENGINE=InnoDB;

INSERT INTO USERS(U_ID,USERNAME,PASSWORD) VALUES(1,'admin','admin');

